language: haskell
addons:
  apt:
    packages:
      - libglfw3-dev
ghc:
  - "8.4"
  - "8.6"
env:
  - PACKAGEDIR="GPipe-GLFW/"
  - PACKAGEDIR="Smoketests/"
before_install: cd ${PACKAGEDIR}
script:
  - cabal v2-build all
